---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Fizilil Home"
subtitle: "Welcome!"
# documentTitle: "Welcome" # Customize the browser tab text
# logo: "./assets/logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
footer: false
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck:
  true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
  # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level.

# Set the default layout and color scheme
defaults:
  layout: "list" # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
stylesheet:
  - "assets/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
# colors:
#   light:
#     highlight-primary: "#3367d6"
#     highlight-secondary: "#4285f4"
#     highlight-hover: "#5a95f5"
#     background: "#f5f5f5"
#     card-background: "#ffffff"
#     text: "#363636"
#     text-header: "#424242"
#     text-title: "#303030"
#     text-subtitle: "#424242"
#     card-shadow: rgba(0, 0, 0, 0.1)
#     link: "#3273dc"
#     link-hover: "#363636"
#     background-image: "assets/your/light/bg.png"
#   dark:
#     highlight-primary: "#3367d6"
#     highlight-secondary: "#4285f4"
#     highlight-hover: "#5a95f5"
#     background: "#131313"
#     card-background: "#2b2b2b"
#     text: "#eaeaea"
#     text-header: "#ffffff"
#     text-title: "#fafafa"
#     text-subtitle: "#f5f5f5"
#     card-shadow: rgba(0, 0, 0, 0.4)
#     link: "#3273dc"
#     link-hover: "#ffdd57"
#     background-image: "assets/your/dark/bg.png"

# Optional message
# message:
#   # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
#   # mapping: # allows to map fields from the remote format to the one expected by Homer
#   #   title: 'id' # use value from field 'id' as title
#   #   content: 'value' # value from field 'value' as content
#   # refreshInterval: 10000 # Optional: time interval to refresh message
#   #
#   # Real example using chucknorris.io for showing Chuck Norris facts as messages:
#   # url: https://api.chucknorris.io/jokes/random
#   # mapping:
#   #   title: 'id'
#   #   content: 'value'
#   # refreshInterval: 10000
#   style: "is-warning"
#   title: "Optional message!"
#   icon: "fa fa-exclamation-triangle"
#   content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  []
  # - name: "Link 1"
  #   icon: "fab fa-github"
  #   url: "https://github.com/bastienwirtz/homer"
  #   target: "_blank" # optional html tag target attribute
  # - name: "link 2"
  #   icon: "fas fa-book"
  #   url: "https://github.com/bastienwirtz/homer"
  # # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
  # # see url field and assets/page.yml used in this example:
  # - name: "Second Page"
  #   icon: "fas fa-file-alt"
  #   url: "#page2"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "User Apps"
    icon: "fas fa-users"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.svg"
        subtitle: "Watch Movies & TV Shows"
        tag: "apps"
        type: "Emby"
        apikey: "d28b069d0c254c6db7713c730be438c9"
        keywords: "jellyfin movies tv shows"
        target: "_blank"
        url: "https://jellyfin.fizilil.ro"
      - name: "Jellyseer"
        logo: "assets/tools/jellyseerr.svg"
        subtitle: "Request Movies & TV Shows"
        tag: "app"
        keywords: "jellyseerr movies tv shows request"
        url: "https://request.fizilil.ro"
        target: "_blank"
      - name: "Server Status"
        logo: "assets/tools/status.png"
        tag: "status"
        keywords: "status jellyfin jellyseerr request"
        url: "https://status.fizilil.ro"
        slug: "fizilil"
        type: "UptimeKuma"
        target: "_blank"
      - name: "Alternative Server Status"
        logo: "assets/tools/status.png"
        subtitle: "Check Server Status Alternative"
        tag: "status"
        keywords: "status jellyfin jellyseerr request"
        url: "https://stats.uptimerobot.com/3n2qXS7WGN"
        target: "_blank"
  - name: "Arr Stack"
    icon: "fas fa-skull-crossbones"
    items:
      - name: "Radarr"
        logo: "assets/tools/radarr.svg"
        # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        tag: "arr"
        url: "https://radarr.fizilil.ro"
        target: "_blank" # optional html a tag target attribute
        type: "Radarr"
        apikey: "93cf30cd2f7f42a0b3e62a75f23e28a6"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.svg"
        # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        tag: "arr"
        url: "https://sonarr.fizilil.ro"
        target: "_blank" # optional html a tag target attribute
        type: "Sonarr"
        apikey: "b8dccfb30ab24bde98af7910a062b019"
      - name: "Bazarr"
        logo: "assets/tools/bazarr.svg"
        # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        tag: "arr"
        url: "https://bazarr.fizilil.ro"
        target: "_blank" # optional html a tag target attribute
        # class: "green" # optional custom CSS class for card, useful with custom stylesheet
        # background: red # optional color for card to set color directly without custom stylesheet
  - name: "Other"
    icon: "fas fa-cogs"
    items:
      - name: "qBittorrent"
        logo: "assets/tools/qbittorrent.svg"
        url: "https://downloader.fizilil.ro" # Your rTorrent web UI, f.e. ruTorrent or Flood.
        tag: "download"
        # type: "qBittorrent"
        # rateInterval: 2000 # Interval for updating the download and upload rates.
        # torrentInterval: 5000 # Interval for updating the torrent count.
        # target: "_blank" # optional html a tag target attribute
      - name: "JellyStat"
        logo: "assets/tools/jellystat.png"
        url: "https://jellystat.fizilil.ro" # Your rTorrent web UI, f.e. ruTorrent or Flood.
        tag: "stats"
        # type: "qBittorrent"
        # rateInterval: 2000 # Interval for updating the download and upload rates.
        # torrentInterval: 5000 # Interval for updating the torrent count.
        target: "_blank" # optional html a tag target attribute
